import { AIProviderConfig, AIProviderId } from "./types";

export const AI_PROVIDERS: Record<AIProviderId, AIProviderConfig> = {
  anthropic: {
    id: "anthropic",
    name: "Anthropic Claude",
    tagline: "Raciocínio avançado e redação técnica refinada",
    description: "Modelos líderes em escrita comercial, análise profunda e formulação de escopos técnicos detalhados.",
    badgeColor: "bg-amber-500/10 text-amber-500 border-amber-500/20",
    keyEnvVar: "ANTHROPIC_API_KEY",
    defaultBaseUrl: "https://api.anthropic.com",
    requiresApiKey: true,
    defaultModel: "claude-3-7-sonnet-20250219",
    modelsEndpoint: "/v1/models",
    models: [
      {
        id: "claude-5-sonnet",
        name: "Claude 5 Sonnet (Next-Gen)",
        description: "Modelo de 5ª geração para raciocínio ultra-avançado e arquitetura.",
        tier: "flagship",
        contextWindow: "1M",
        isNew: true,
      },
      {
        id: "claude-5-opus",
        name: "Claude 5 Opus (Next-Gen)",
        description: "Inteligência máxima para análises críticas e síntese executiva profunda.",
        tier: "reasoning",
        contextWindow: "1M",
        isNew: true,
      },
      {
        id: "claude-3-7-sonnet-20250219",
        name: "Claude 3.7 Sonnet (Mais Novo)",
        description: "Modelo híbrido com modo de pensamento adaptativo em tempo real.",
        tier: "flagship",
        contextWindow: "200k",
        isNew: true,
      },
      {
        id: "claude-3-5-sonnet-20241022",
        name: "Claude 3.5 Sonnet (v2)",
        description: "Altíssima precisão técnica, geração de código e documentos.",
        tier: "flagship",
        contextWindow: "200k",
      },
      {
        id: "claude-3-5-haiku-20241022",
        name: "Claude 3.5 Haiku",
        description: "Ultra rápido e econômico para tarefas rotineiras e classificação.",
        tier: "fast",
        contextWindow: "200k",
      },
      {
        id: "claude-3-opus-20240229",
        name: "Claude 3 Opus",
        description: "Análise complexa e síntese textual profunda.",
        tier: "reasoning",
        contextWindow: "200k",
      },
    ],
  },

  gemini: {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Janela de contexto massiva e velocidade de ponta",
    description: "Modelos multimodais de alta velocidade e capacidade de processar grandes históricos de dados.",
    badgeColor: "bg-blue-500/10 text-blue-500 border-blue-500/20",
    keyEnvVar: "GEMINI_API_KEY",
    defaultBaseUrl: "https://generativelanguage.googleapis.com",
    requiresApiKey: true,
    defaultModel: "gemini-2.0-flash",
    modelsEndpoint: "https://generativelanguage.googleapis.com/v1beta/models",
    models: [
      {
        id: "gemini-3.7-flash",
        name: "Gemini 3.7 Flash (Next-Gen)",
        description: "Nova geração Gemini com velocidade quântica e contexto ampliado.",
        tier: "flagship",
        contextWindow: "4M",
        isNew: true,
      },
      {
        id: "gemini-3.1-pro",
        name: "Gemini 3.1 Pro (Next-Gen)",
        description: "Alta capacidade de raciocínio lógico e auditoria documental.",
        tier: "reasoning",
        contextWindow: "4M",
        isNew: true,
      },
      {
        id: "gemini-3.1-flash",
        name: "Gemini 3.1 Flash",
        description: "Respostas ultra-rápidas para consultas cotidianas no ERP.",
        tier: "fast",
        contextWindow: "2M",
        isNew: true,
      },
      {
        id: "gemini-2.0-flash",
        name: "Gemini 2.0 Flash (Mais Novo)",
        description: "Geração de texto em tempo real com excelente precisão multimodal.",
        tier: "flagship",
        contextWindow: "1M",
        isNew: true,
      },
      {
        id: "gemini-2.0-flash-thinking-exp-01-21",
        name: "Gemini 2.0 Flash Thinking (Raciocínio)",
        description: "Modo com cadeia de pensamentos detalhada para resolução de problemas.",
        tier: "reasoning",
        contextWindow: "1M",
        isNew: true,
      },
      {
        id: "gemini-2.0-flash-lite",
        name: "Gemini 2.0 Flash Lite",
        description: "Modelo ultra econômico e rápido para consultas frequentes.",
        tier: "fast",
        contextWindow: "1M",
        isNew: true,
      },
      {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        description: "Janela de 2M tokens para análise de relatórios extensos e auditorias.",
        tier: "reasoning",
        contextWindow: "2M",
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        description: "Rápido e balanceado para automações e respostas instantâneas.",
        tier: "fast",
        contextWindow: "1M",
      },
    ],
  },

  openai: {
    id: "openai",
    name: "OpenAI",
    tagline: "Modelos pioneiros em inteligência geral e raciocínio",
    description: "A família GPT e os novos modelos o-series para lógica e planejamento complexo.",
    badgeColor: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
    keyEnvVar: "OPENAI_API_KEY",
    defaultBaseUrl: "https://api.openai.com",
    requiresApiKey: true,
    defaultModel: "gpt-4o",
    modelsEndpoint: "https://api.openai.com/v1/models",
    models: [
      {
        id: "gpt-5.6",
        name: "GPT 5.6 (Next-Gen)",
        description: "Próxima geração com inteligência autônoma e raciocínio unificado.",
        tier: "flagship",
        contextWindow: "500k",
        isNew: true,
      },
      {
        id: "gpt-5",
        name: "GPT-5 (Flagship)",
        description: "Modelo de 5ª geração com compreensão profunda de negócios.",
        tier: "flagship",
        contextWindow: "256k",
        isNew: true,
      },
      {
        id: "fable-5",
        name: "Fable 5 (Creative & Narrative)",
        description: "Modelo especializado em redação persuasiva e argumentos comerciais.",
        tier: "specialized",
        contextWindow: "256k",
        isNew: true,
      },
      {
        id: "gpt-4.5-preview",
        name: "GPT-4.5 Preview (Mais Novo)",
        description: "Maior modelo com inteligência factual superior e empatia.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "gpt-4o",
        name: "GPT-4o (Omni)",
        description: "Inteligência de ponta para todas as tarefas com alta velocidade.",
        tier: "flagship",
        contextWindow: "128k",
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        description: "Opção rápida e econômica para respostas imediatas.",
        tier: "fast",
        contextWindow: "128k",
      },
      {
        id: "o3-mini",
        name: "o3-mini (Raciocínio Rápido)",
        description: "Modelo especializado em raciocínio lógico, cálculo e normas.",
        tier: "reasoning",
        contextWindow: "200k",
        isNew: true,
      },
      {
        id: "o1",
        name: "o1 (Raciocínio Profundo)",
        description: "Raciocínio detalhado antes de responder problemas difíceis.",
        tier: "reasoning",
        contextWindow: "200k",
      },
      {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        description: "Conhecimento consolidado e alta confiabilidade.",
        tier: "flagship",
        contextWindow: "128k",
      },
    ],
  },

  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    tagline: "Raciocínio avançado e altíssimo custo-benefício",
    description: "Modelos abertos de ponta com capacidade incrível de raciocínio lógico e estruturação de dados.",
    badgeColor: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
    keyEnvVar: "DEEPSEEK_API_KEY",
    defaultBaseUrl: "https://api.deepseek.com",
    requiresApiKey: true,
    defaultModel: "deepseek-chat",
    modelsEndpoint: "https://api.deepseek.com/models",
    models: [
      {
        id: "deepseek-v4",
        name: "DeepSeek V4 (Next-Gen)",
        description: "Próxima geração de inteligência aberta e arquitetura MoE avançada.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "deepseek-r2",
        name: "DeepSeek R2 (Reasoner)",
        description: "Raciocínio formal e cadeias lógicas matemáticas ultra-profundas.",
        tier: "reasoning",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "deepseek-chat",
        name: "DeepSeek V3 (Chat)",
        description: "Modelo geral de alta inteligência e respostas muito rápidas.",
        tier: "flagship",
        contextWindow: "64k",
        isNew: true,
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek R1 (Reasoner)",
        description: "Modelo de raciocínio profundo com cadeia de pensamentos detalhada.",
        tier: "reasoning",
        contextWindow: "64k",
        isNew: true,
      },
    ],
  },

  groq: {
    id: "groq",
    name: "Groq (Ultra-Rápido)",
    tagline: "Inferência em milissegundos via chips LPU",
    description: "Velocidade impressionante para respostas sem atraso perceptível no chat e nas buscas.",
    badgeColor: "bg-orange-500/10 text-orange-500 border-orange-500/20",
    keyEnvVar: "GROQ_API_KEY",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    requiresApiKey: true,
    defaultModel: "llama-3.3-70b-versatile",
    modelsEndpoint: "https://api.groq.com/openai/v1/models",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        description: "O modelo open-source mais forte da Meta com velocidade extrema.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "deepseek-r1-distill-llama-70b",
        name: "DeepSeek R1 Distill Llama 70B",
        description: "Raciocínio estilo DeepSeek R1 rodando na velocidade Groq.",
        tier: "reasoning",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        description: "Geração ultrarrápida para respostas instantâneas.",
        tier: "fast",
        contextWindow: "128k",
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        description: "Arquitetura MoE versátil e ágil.",
        tier: "fast",
        contextWindow: "32k",
      },
    ],
  },

  mistral: {
    id: "mistral",
    name: "Mistral AI",
    tagline: "Modelos europeus de alta precisão e versatilidade",
    description: "Excelente desempenho em múltiplos idiomas, elaboração de documentos e lógica de negócios.",
    badgeColor: "bg-indigo-500/10 text-indigo-500 border-indigo-500/20",
    keyEnvVar: "MISTRAL_API_KEY",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    requiresApiKey: true,
    defaultModel: "mistral-large-latest",
    modelsEndpoint: "https://api.mistral.ai/v1/models",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large 2 (Mais Novo)",
        description: "Modelo topo de linha da Mistral para raciocínio complexo e redação.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small 3 (2501)",
        description: "Rápido, econômico e eficiente para respostas diárias.",
        tier: "fast",
        contextWindow: "32k",
        isNew: true,
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        description: "Especialista em lógica, estruturas de dados e consultas técnicas.",
        tier: "specialized",
        contextWindow: "32k",
      },
      {
        id: "pixtral-large-latest",
        name: "Pixtral Large",
        description: "Modelo multimodal para análise de documentos e imagens.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
    ],
  },

  xai: {
    id: "xai",
    name: "xAI (Grok)",
    tagline: "Inteligência analítica moderna e direta",
    description: "Modelos Grok desenvolvidos pela equipe da xAI.",
    badgeColor: "bg-purple-500/10 text-purple-500 border-purple-500/20",
    keyEnvVar: "XAI_API_KEY",
    defaultBaseUrl: "https://api.x.ai/v1",
    requiresApiKey: true,
    defaultModel: "grok-2-latest",
    modelsEndpoint: "https://api.x.ai/v1/models",
    models: [
      {
        id: "grok-3",
        name: "Grok 3 (Next-Gen)",
        description: "Modelo de 3ª geração da xAI com capacidades analíticas e científicas.",
        tier: "flagship",
        contextWindow: "1M",
        isNew: true,
      },
      {
        id: "grok-2-latest",
        name: "Grok 2 (Mais Novo)",
        description: "Modelo de ponta com alta precisão e raciocínio analítico.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "grok-2-vision-1212",
        name: "Grok 2 Vision",
        description: "Capacidade de leitura de relatórios visuais e gráficos.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "grok-beta",
        name: "Grok Beta",
        description: "Versão padrão de desenvolvimento ágil.",
        tier: "fast",
        contextWindow: "128k",
      },
    ],
  },

  cohere: {
    id: "cohere",
    name: "Cohere",
    tagline: "Especialista em dados corporativos e RAG",
    description: "Foco em sumarização de dados empresariais, busca e respostas precisas.",
    badgeColor: "bg-teal-500/10 text-teal-500 border-teal-500/20",
    keyEnvVar: "COHERE_API_KEY",
    defaultBaseUrl: "https://api.cohere.com/v2",
    requiresApiKey: true,
    defaultModel: "command-r-plus-08-2024",
    modelsEndpoint: "https://api.cohere.com/v1/models",
    models: [
      {
        id: "command-r-plus-08-2024",
        name: "Command R+ (08-2024)",
        description: "Modelo corporativo premium para análise e geração de relatórios.",
        tier: "flagship",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "command-r-08-2024",
        name: "Command R",
        description: "Equilíbrio entre custo e desempenho para empresas.",
        tier: "fast",
        contextWindow: "128k",
      },
    ],
  },

  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    tagline: "Acesso unificado a +200 modelos via 1 única chave",
    description: "Permite usar qualquer modelo do mercado (Claude, GPT, Llama, Qwen, DeepSeek) centralizando cobrança e limites.",
    badgeColor: "bg-violet-500/10 text-violet-500 border-violet-500/20",
    keyEnvVar: "OPENROUTER_API_KEY",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    requiresApiKey: true,
    defaultModel: "anthropic/claude-3.7-sonnet",
    modelsEndpoint: "https://openrouter.ai/api/v1/models",
    models: [
      {
        id: "anthropic/claude-3.7-sonnet",
        name: "Claude 3.7 Sonnet (via OpenRouter)",
        description: "Acesso direto ao modelo mais novo da Anthropic.",
        tier: "flagship",
        contextWindow: "200k",
        isNew: true,
      },
      {
        id: "openai/gpt-5",
        name: "GPT-5 (via OpenRouter)",
        description: "Modelo de 5ª geração OpenAI.",
        tier: "flagship",
        contextWindow: "256k",
        isNew: true,
      },
      {
        id: "deepseek/deepseek-r1",
        name: "DeepSeek R1 (via OpenRouter)",
        description: "Raciocínio avançado aberto.",
        tier: "reasoning",
        contextWindow: "128k",
        isNew: true,
      },
      {
        id: "openai/gpt-4o-2024-11-20",
        name: "GPT-4o (via OpenRouter)",
        description: "Modelo oficial da OpenAI.",
        tier: "flagship",
        contextWindow: "128k",
      },
      {
        id: "meta-llama/llama-3.3-70b-instruct",
        name: "Llama 3.3 70B Instruct",
        description: "Modelo aberto de alta inteligência.",
        tier: "flagship",
        contextWindow: "128k",
      },
      {
        id: "google/gemini-2.0-flash-001",
        name: "Gemini 2.0 Flash (via OpenRouter)",
        description: "Google Gemini 2.0 Flash.",
        tier: "fast",
        contextWindow: "1M",
        isNew: true,
      },
    ],
  },

  ollama: {
    id: "ollama",
    name: "Ollama (IA Local & Offline)",
    tagline: "Privacidade total rodando na sua própria máquina",
    description: "Sem custos de API e 100% privado. Roda modelos locais através do Ollama em http://localhost:11434.",
    badgeColor: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
    keyEnvVar: "OLLAMA_BASE_URL",
    defaultBaseUrl: "http://localhost:11434",
    requiresApiKey: false,
    defaultModel: "llama3.3",
    modelsEndpoint: "http://localhost:11434/api/tags",
    models: [
      {
        id: "llama3.3",
        name: "Llama 3.3 (Local)",
        description: "Modelo local completo da Meta.",
        tier: "flagship",
      },
      {
        id: "deepseek-r1",
        name: "DeepSeek R1 (Local)",
        description: "Raciocínio profundo local (distill ou full).",
        tier: "reasoning",
        isNew: true,
      },
      {
        id: "qwen2.5",
        name: "Qwen 2.5 (Local)",
        description: "Excelente em código, tabelas e raciocínio técnico.",
        tier: "flagship",
      },
      {
        id: "mistral",
        name: "Mistral 7B (Local)",
        description: "Leve e rápido para qualquer máquina com CPU/GPU.",
        tier: "fast",
      },
    ],
  },

  custom: {
    id: "custom",
    name: "Custom / OpenAI-Compatible",
    tagline: "Conecte qualquer servidor compatível (LM Studio, vLLM, Azure)",
    description: "Permite especificar qualquer URL base (ex: LM Studio, vLLM, Together AI, Fireworks) e nome de modelo personalizado.",
    badgeColor: "bg-pink-500/10 text-pink-500 border-pink-500/20",
    keyEnvVar: "CUSTOM_AI_API_KEY",
    defaultBaseUrl: "http://localhost:1234/v1",
    requiresApiKey: false,
    defaultModel: "default-model",
    modelsEndpoint: "/v1/models",
    models: [
      {
        id: "default-model",
        name: "Modelo Customizado Padrão",
        description: "O modelo configurado no seu servidor customizado.",
        tier: "flagship",
      },
    ],
  },
};

export const DEFAULT_AI_PROVIDER: AIProviderId = "gemini";
